services:
  postgres:
    image: postgres:13
    container_name: rss_postgres
    environment:
      POSTGRES_DB: parser
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
