"""Updated tables

Revision ID: 1d78bb996d1e
Revises: e5e9f918ed3c
Create Date: 2024-10-03 00:07:18.867111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d78bb996d1e'
down_revision: Union[str, None] = 'e5e9f918ed3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_user_origin', 'user_source_association', type_='unique')
    op.create_unique_constraint('idx_unique_user_source', 'user_source_association', ['user_id', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_user_source', 'user_source_association', type_='unique')
    op.create_unique_constraint('idx_unique_user_origin', 'user_source_association', ['user_id', 'source_id'])
    # ### end Alembic commands ###
