"""Updated tables

Revision ID: e5e9f918ed3c
Revises: b1bc821261bd
Create Date: 2024-10-02 23:18:50.011823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e9f918ed3c'
down_revision: Union[str, None] = 'b1bc821261bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'news', ['id'])
    op.create_unique_constraint(None, 'sources', ['id'])
    op.create_unique_constraint(None, 'user_source_association', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_source_association', type_='unique')
    op.drop_constraint(None, 'sources', type_='unique')
    op.drop_constraint(None, 'news', type_='unique')
    # ### end Alembic commands ###
